### ISSUE TITLE
你好，是否支持自定义成此样式的

### ISSUE THREAD

**Issue by azheng95** [jenly1314/SplitEditText#2]
![1691747094301](https://github.com/jenly1314/SplitEditText/assets/23047162/d1f2d1cd-345a-487d-be65-ce5bf36a2106)
你好，是否支持自定义成此样式的 ●●●●●●  。忽略图片中的文字信息。

**Comment by jenly1314** [comment]
理论上应该是可以的；
可以查看readme属性相关说明，通过设置**setStrokeWidth**将描边加粗，和**setBorderCornerRadius**配合使用，最终绘制成一个实心圆●， **setCipherMask** 使用密文；这样应该能达到你截图上的效果。
